### ISSUE TITLE
Alternative Backends

### ISSUE THREAD

**Issue by bitmappergit** [mpw/ObjectiveTcc#1]
Hey, you said that LLVM was too complex, I've been looking at backends for my personal projects, and I came across this https://c9x.me/compile/.
Would this be of any use?

(Sorry, don't know of any other way of mentioning this)

**Comment by mpw** [comment]
Thanks for the pointer, QBE is definitely an option. In fact, I have a copy of QBE on my dev machine :-)

One thing I like about tcc is that it goes directly to to machine code without an intermediate representation, which makes it extremely efficient both in theory and in practice.

Thanks again!
